
INSERT into recipes (name ,thumbnail_photo_url, preparation_time , cooking_time , serving , ingredients , instructions , posted_by, account_id , user_id ) VALUES ( 'Rice', 'https://images.unsplash.com/photo-1625980319455-985e5442c5ae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzV8fHJpY2V8ZW58MHx8MHx8&auto=format&fit=crop&w=900&q=60', 5, 20, 4, '2 cups Rice , 4 cups Water', 'Wash rice, Add water, boil rice in water', 'Alice', 1, 1 );
INSERT into recipes (name ,thumbnail_photo_url, preparation_time , cooking_time , serving , ingredients , instructions , posted_by, account_id , user_id ) VALUES ( 'Veggie Wrap', 'https://images.unsplash.com/photo-1562059390-a761a084768e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8d3JhcHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=900&q=60', 20, 5, 4, 'Finely chopped bell peppers, lettuce, onion, tomatoes, cucumber, jalapeno sauce, tortilla wrap', 'Place lettuce on the wrap, spread chopped veggies , add jalapeno sauce and make a wrap.','Alex', 1, 1 );
INSERT into recipes (name ,thumbnail_photo_url,  preparation_time , cooking_time , serving , ingredients , instructions , posted_by, account_id , user_id ) VALUES ( 'Jello', 'https://images.unsplash.com/photo-1597384462648-87f29203a5bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 15, 30, 3, '2 packets jello powder, water', 'Bring water to a boil, add jello powder , freeze it','Anna', 1, 1 );
INSERT into recipes (name ,thumbnail_photo_url,  preparation_time , cooking_time , serving , ingredients , instructions , posted_by, account_id , user_id ) VALUES ( 'Fruit Salad', 'https://images.unsplash.com/photo-1613082487279-1e16f1e81505?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2352&q=80', 20, 5, 2, 'Fresh cut fruits, custard powder, milk and sugar', 'Mix custard powder with milk and bring it to boil, add sugar and let it cool, mix fresh cut fruits and refrigerate', 'Alice', 1, 1 );


INSERT into recipes (name ,thumbnail_photo_url, preparation_time , cooking_time , serving , ingredients , instructions , posted_by, account_id , user_id ) VALUES ( 'Lemanade', 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bGVtb25hZGV8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60', 5, 20, 4, '2 cups Rice , 4 cups Water', 'Wash rice, Add water, boil rice in water', 'Kira', 2, 2 );
INSERT into recipes (name ,thumbnail_photo_url, preparation_time , cooking_time , serving , ingredients , instructions , posted_by, account_id , user_id ) VALUES ( 'Veggie Wrap', 'https://images.unsplash.com/photo-1584947897804-408958123f1d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80', 20, 5, 4, 'Finely chopped bell peppers, lettuce, onion, tomatoes, cucumber, jalapeno sauce, tortilla wrap', 'Place lettuce on the wrap, spread chopped veggies , add jalapeno sauce and make a wrap.', 'Jane', 3, 3 );

INSERT into recipes (name ,thumbnail_photo_url,  preparation_time , cooking_time , serving , ingredients , instructions , posted_by, account_id , user_id ) VALUES ( 'Custard', 'https://images.unsplash.com/photo-1592909572567-9b6d34170971?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=994&q=80', 15, 40, 6, '1 packet custard powder, Milk, Sugar , Salt', 'Mix everything together and heat it up', 'Kira', 2, 2 );
INSERT into recipes (name ,thumbnail_photo_url,  preparation_time , cooking_time , serving , ingredients , instructions , posted_by, account_id , user_id ) VALUES ( 'Custard', 'https://images.unsplash.com/photo-1505253213348-ce3e0ff1f0cc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80',  15, 40, 6, '1 packet custard powder, Milk, Sugar , Salt', 'Mix everything together and heat it up', 'Jane', 3, 3 );

INSERT into recipes (name ,thumbnail_photo_url,  preparation_time , cooking_time , serving , ingredients , instructions ,  posted_by, account_id , user_id ) VALUES ( 'Jello', 'https://images.unsplash.com/photo-1597384462648-87f29203a5bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 15, 30, 3, '2 packets jello powder, water', 'Bring water to a boil, add jello powder , freeze it', 'Samantha', 4, 5 );
INSERT into recipes (name ,thumbnail_photo_url,  preparation_time , cooking_time , serving , ingredients , instructions ,  posted_by, account_id , user_id ) VALUES ( 'Fruit Salad', 'https://images.unsplash.com/photo-1613082487279-1e16f1e81505?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2352&q=80', 20, 5, 2, 'Fresh cut fruits, custard powder, milk and sugar', 'Mix custard powder with milk and bring it to boil, add sugar and let it cool, mix fresh cut fruits and refrigerate', 'Ann', 4, 6 );
INSERT into recipes (name ,thumbnail_photo_url,  preparation_time , cooking_time , serving , ingredients , instructions ,  posted_by, account_id , user_id ) VALUES ( 'Chocolate Milkshake','https://images.unsplash.com/photo-1591864384134-8a21ffb51cb5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 15, 5, 4, 'Chocolate syrup, cream, milk and sugar', 'Blend chocolate syrup with milk and cream, add sugar needed', 'Isa', 4, 7 );
INSERT into recipes (name ,thumbnail_photo_url, preparation_time , cooking_time , serving , ingredients , instructions ,  posted_by, account_id , user_id ) VALUES ( 'Veggie Wrap', 'https://images.unsplash.com/photo-1584947897804-408958123f1d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80', 20, 5, 4, 'Finely chopped bell peppers, lettuce, onion, tomatoes, cucumber, jalapeno sauce, tortilla wrap', 'Place lettuce on the wrap, spread chopped veggies , add jalapeno sauce and make a wrap.', 'Jane', 4, 5);
